# Generated by Django 3.2.25 on 2025-03-20 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_cart_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
    ]
